name: build windows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: install yq
        run: choco install yq
      
      - name: modify buildNumber in Runner.rc
        run: sed -i "s/1,0,0/"$(date '+%y'),$(date '+%m%d'),$(date '+%H%M')"/g" Runner.rc
        shell: bash

      - name: modify version in Runner.rc
        run: sed -i "s/1.0.0/$(yq '.version' pubspec.yaml)/g" Runner.rc
        shell: bash

      - name: check result
        run: cat Runner.rc
      
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
  
      - name: enable flutter desktop support
        run: flutter config --enable-windows-desktop
      
      - name: build windows
        run: flutter build windows

      - name: upload app
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build\windows\runner\Release
          retention-days: 1