name: parse yaml

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.27.2
        with:
          cmd: yq '.version' pubspec.yaml
