name: parse yaml

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install yq
        run: choco install yq
      
      - name: get app version
        run: yq '.version' pubspec.yaml

      # - run: date '+%m%d%H%M'
      - run: Get-Date -format "yyyyMMdd"

      - name: modify app version
        run: yq '.version' pubspec.yaml