name: parse yaml - macos

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: get build number
        id: time
        run: echo ::set-output name=number::$(date '+%Y%m%d%H%M')

      - name: install yq
        run: brew install yq
      
      - name: get app version
        id: version
        run: echo ::set-output name=version::$(yq '.version' pubspec.yaml)

      - name: modify app version
        # a=3.3.3 b=333 c=$a+$b yq -i ".version=env(c)" t.yml
        run: version=$( steps.version.outputs.version ) number=$( steps.time.outputs.number ) str=$version+$number yq -i '.version=env(str)' pubspec.yaml

      - name: get app version
        run: yq '.version' pubspec.yaml