name: parse yaml - windows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: install yq
        run: choco install yq
      
      - name: modify app version
        run: version=$(yq '.version' pubspec.yaml) number=$(date '+%Y%m%d%H%M') str=$version+$number yq -i '.version=env(str)' pubspec.yaml
        shell: bash

      - name: get app version
        run: yq '.version' pubspec.yaml