name: parse yaml - windows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      # - run: date '+%m%d%H%M'
      - name: get build number
        id: time
        run: Get-Date -format "yyyyMMdd"

      - name: install yq
        run: choco install yq
      
      - name: get app version
        run: yq '.version' pubspec.yaml

      - name: modify app version
        run: yq -i '.version="100+${{ steps.time.outputs.stdout }}"' pubspec.yaml

      - name: get app version
        run: yq '.version' pubspec.yaml