name: parse yaml - windows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: install yq
        run: choco install yq
      
      - name: modify Runner.rc
        run: sed -i "s/1,0,0/"$(date '+%Y'),$(date '+%m%d'),$(date '+%H%M')"/g" "s/1.0.0/$(yq '.version' pubspec.yaml)/g" Runner.rc
            #  sed -i "s/1.0.0/$(yq '.version' pubspec.yaml)/g" Runner.rc
        shell: bash

      - name: check result
        run: cat Runner.rc